### ISSUE TITLE
作者能改一下做成DLL吗？

### ISSUE THREAD

**Issue by Liujunhua007** [charlotte-xiao/NCM2MP3-By-JAVA#16]
曾经2.4版本的时候，大概18年，那时刚出NCM格式的时候，吾爱破解论坛上有人做了个DLL解NCM，可以在下载的时候自动完成解密。好处就是比起GUI和命令行这些工具解密后生成新文件这种方式，不会丢失匹配信息，网易云的匹配有些不准确，会导致一部分歌曲匹配不到信息？总之很奇葩····

**Comment by Liujunhua007** [comment]
![QQ截图20230520021120](https://github.com/charlotte-xiao/NCM2MP3/assets/62129047/9d95545d-dd00-40c0-8311-ee0d3b614e6a)
大概是这个dll

**Comment by charlotte-xiao** [comment]
Sorry, I have no experience with open ddl scripts. If you have a better suggestion, welcome to submit a PR
