### ISSUE TITLE
转换速度略慢

### ISSUE THREAD

**Issue by CodingFatman** [charlotte-xiao/NCM2MP3-By-JAVA#18]
转换500多首歌，界面就卡住了，建议是否可以调整为多线程操作，同时界面上要保持能够和用户交互。
当然这个要求可能略显过分，毕竟只是个开源的小工具，这只是个建议，望采纳。

**Comment by charlotte-xiao** [comment]
1. 可以尝试修改一下`src/main/java/executor/AsyncTaskExecutor.java`中相关的线程池的参数进行优化
2. 制定JVM参数，进行JVM性能优化
