### ISSUE TITLE
转换失败

### ISSUE THREAD

**Issue by LonelyMarch** [charlotte-xiao/NCM2MP3-By-JAVA#3]
同时转化几十个.ncm文件时，部分文件会显示转换失败，但在输出文件夹里却有这些文件转换后的文件，并且可以打开播放。

C:\Users\Administrator>java --version
java 16 2021-03-16
Java(TM) SE Runtime Environment (build 16+36-2231)
Java HotSpot(TM) 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

**Comment by LonelyMarch** [comment]
>>>java --version
java 16 2021-03-16
Java(TM) SE Runtime Environment (build 16+36-2231)
Java HotSpot(TM) 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

**Comment by charlotte-xiao** [comment]
该问题可能是由于不同操作系统，部分文件的路径划分符号//和\\问题导致的，将进行修复
见[question1](https://github.com/charlotte-xiao/NCM2MP3/issues/1)
