### ISSUE TITLE
转码后字符乱码

### ISSUE THREAD

**Issue by Missdrop** [charlotte-xiao/NCM2MP3-By-JAVA#4]
如题
![image](https://user-images.githubusercontent.com/101849047/165771307-8976e4ab-0df6-4bdb-abe3-c4683fe4f29a.png)
解密后出现标题等乱码现象

**Comment by charlotte-xiao** [comment]
使用new String()的时候，使用的defaultCharset，"ISO-8859-1"的编码格式导致的乱码，最新代码已经修复。
