### ISSUE TITLE
乱码解决方案之一

### ISSUE THREAD

**Issue by wsuncle01** [charlotte-xiao/NCM2MP3-By-JAVA#5]

**Comment by wsuncle01** [comment]
#encoding:utf-8
from turtle import title
from mutagen.id3 import ID3, APIC, TIT2, TPE1, TALB
import os


def get_mp3(mp3path):
    mp3_list = []
    for dirs, dirnames, files in os.walk(mp3path):
        for file in files:
            if file.endswith('.mp3'):
                mp3_list.append(dirs+'/'+file)
    return mp3_list


def SetMp3Info(mp3file, info):
    songFile = ID3(mp3file)
    songFile['TIT2'] = TIT2(  # 插入歌名
        encoding=3,
        text=info['title']
    )
    songFile['TPE1'] = TPE1(  # 插入第一演奏家、歌手、等
        encoding=3,
        text=info['artist']
    )
    songFile['TALB'] = TALB(  # 插入专辑名
        encoding=3,
        text=info['album']
    )
    songFile.save()


if __name__ == '__main__':
    mp3path = r'C:/Users/drago/Desktop/1/new'

    mp3_list = get_mp3(mp3path)
    for mp3file in mp3_list:
        newname = mp3file
        songtitle = newname.split(' - ')
        #print(songtitle)
        artist=songtitle[0].replace('C:/Users/drago/Desktop/1/new/','')
        title=songtitle[1].replace('.mp3','')
        #print(artist,title)
        info = {'title': title,
                'artist': artist,
                'album': artist}
        SetMp3Info(mp3file, info)

**Comment by wsuncle01** [comment]
#encoding:utf-8
from turtle import title
from mutagen.id3 import ID3, APIC, TIT2, TPE1, TALB
import os


def get_mp3(mp3path):
    mp3_list = []
    for dirs, dirnames, files in os.walk(mp3path):
        for file in files:
            if file.endswith('.mp3'):
                mp3_list.append(dirs+'/'+file)
    return mp3_list


def SetMp3Info(mp3file, info):
    songFile = ID3(mp3file)
    songFile['TIT2'] = TIT2(  # 插入歌名
        encoding=3,
        text=info['title']
    )
    songFile['TPE1'] = TPE1(  # 插入第一演奏家、歌手、等
        encoding=3,
        text=info['artist']
    )
    songFile['TALB'] = TALB(  # 插入专辑名
        encoding=3,
        text=info['album']
    )
    songFile.save()


if __name__ == '__main__':
    mp3path = r'path'

    mp3_list = get_mp3(mp3path)
    for mp3file in mp3_list:
        newname = mp3file
        songtitle = newname.split(' - ')
        #print(songtitle)
        artist=songtitle[0].replace('path','')
        title=songtitle[1].replace('.mp3','')
        #print(artist,title)
        info = {'title': title,
                'artist': artist,
                'album': artist}
        SetMp3Info(mp3file, info)

**Comment by charlotte-xiao** [comment]
谢谢提供修复思路。

**Comment by charlotte-xiao** [comment]
原问题见：https://github.com/charlotte-xiao/NCM2MP3/issues/4
