### ISSUE TITLE
好像这有点问题

### ISSUE THREAD

**Issue by LonelyMarch** [charlotte-xiao/NCM2MP3-By-JAVA#7]
![image](https://user-images.githubusercontent.com/63410167/208871859-ae9d8399-b9ea-4219-bd49-d10c388ce125.png)
.\NCM2MP3\src\main\java\view\view.java:100
貌似掉了个大括号？

**Comment by charlotte-xiao** [comment]
As you can see this code:
`if ("bord\u0065r".equals(e.getPropertyName())) throw new RuntimeException();`
it just uses the line break after the string `bord\u0065r`, it doesn't have an error.
